title: Cooler
logo: /assets/img/cooler_logo6.png
description: Scalable massive sparse maps
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

github:
  zip_url: https://github.com/mirnylab/cooler/archive/v0.8.2.zip
  tar_url: https://github.com/mirnylab/cooler/archive/v0.8.2.tar.gz
  repository_url: https://github.com/mirnylab/cooler
